---
title: "Graphics R-Markdown"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    keep_md: yes
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: center
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Categorical Data

```{r}
pon <- read.csv("201709-CAH_PulseOfTheNation.csv")

# Pivot Table

pon_pivot <- table(pon$Gender,pon$Political.Affiliation)

pon_pivot

```

### Bar Chart

```{r}
# Simple side by side

barplot(pon_pivot, beside = T)

# Prettier

barplot(pon_pivot, ylab="Frequency", xlab="Party", main="Side-By-Side Bar Chart", col=c("blue", "pink", "purple" , "green" ), beside=T, width=.3)

legend("topright", title="Gender", legend= sort(unique(pon$Gender)), fill =c("blue", "pink", "purple" , "green" ), box.lty=0)
```

```{r}
ratings <- c("G","PG","PG-13", "R", "NC-17")
percents <- c(8,24,10,55,3)


barplot(percents, names.arg = ratings)

movies <- data.frame(ratings,percents)

movies$ratings <- factor(movies$ratings, levels = movies$ratings[order(movies$percents, decreasing = TRUE)])

ggplot(movies, aes(ratings,percents)) + geom_bar(stat = "identity")
```

### Pie Chart

```{r}
pon_pie <- table(pon$Political.Affiliation)

pie(pon_pie)
```


```{r}
ratings <- c("G","PG","PG-13", "R", "NC-17")
percents <- c(8,24,10,55,3)

pie(percents, ratings)
```



## Quantitative Graphs

### Dotplot

```{r}
ggplot(pon, aes(x = Age)) + geom_dotplot(binwidth = .5)

ggplot(pon, aes(x = Age, fill = factor(Political.Affiliation))) + geom_dotplot(binwidth = .8)
```

### Histogram

```{r}
hist(pon$Age)

ggplot(pon, aes(x = Age)) + geom_histogram(binwidth = 5, color = "blue")

```

### Stem and Leaf

```{r}
stem(pon$Income)
```

```{r}
data <- c(310,307,345,324,305,301,290,307)

stem(data)
stem(data, scale = 2)
```

### Boxplot

```{r}
boxplot(data, horizontal = T)

df.stuff <- data.frame(data)
ggplot(df.stuff,aes("stuff",data)) + geom_boxplot() +
    geom_jitter(shape = 15, color = "steelblue", position = position_jitter(width = 0.21)) + coord_flip()
```

## Numerical

### Summary

```{r}
summary(data)
```

### Standard Deviation

```{r}
sd(data)
```


### Standard Deviation by Hand

```{r}
cowboys <- c(310,307,345,324,305,301,290,307)

sdbh <- data.frame("Weight"= cowboys)
cowboy.mean <- mean(cowboys)
sdbh$deviations <- cowboys - cowboy.mean
sdbh$sqdev <- (sdbh$deviations)^2

sumsqdev <- sum(sdbh$sqdev)

Var.cowboys <- sumsqdev / (length(cowboys)-1)

var(cowboys)

sd.cowboys <- sqrt(Var.cowboys)

sd(cowboys)
```

## Normal Curve

### Percentile

```{r}
# draw the normal curve
curve(dnorm(x,0,1), xlim=c(-4,4), main="Normal density")
 
# define shaded region
from.z <- -4
to.z <- qnorm(.4)
 
S.x  <- c(from.z, seq(from.z, to.z, 0.01), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 0.01)), 0)
polygon(S.x,S.y, col="red")
```

### Whole Standard Deviations

```{r}
# First: Calculate stanine breaks (on a z scale)
stan.z <- c(seq(-4, 4))
 
# Second: get cumulative probabilities for these z values
stan.PR <- pnorm(stan.z)
 
# define a color ramp from blue to red (... or anything else ...)
c_ramp <- colorRamp(c("darkblue", "red"), space="Lab")
 
# draw the normal curve, without axes; reduce margins on left, top, and right
par(mar=c(2,0,0,0))
curve(dnorm(x,0,1), xlim=c(-4,4), ylim=c(-0.03, .45), xlab="", ylab="", axes=FALSE)

# Calculate polygons for each stanine region
# S.x = x values of polygon boundary points, S.y = y values
for (i in 1:(length(stan.z)-1)) {
    S.x  <- c(stan.z[i], seq(stan.z[i], stan.z[i+1], 0.01), stan.z[i+1])
    S.y  <- c(0, dnorm(seq(stan.z[i], stan.z[i+1], 0.01)), 0)
    polygon(S.x,S.y, col=rgb(c_ramp(i/9), max=255))
}

# print stanine values in white
# font = 2 prints numbers in boldface
text(seq(-3,3), 0.015, label=-3:3, col="white", font=2)
 
# print cumulative probabilities in black below the curve
text(seq(-3,3), -0.015, label=paste(round(stan.PR[-c(1, 6)], 5)*100, "%", sep=""), col="black", adj=.5, cex=.8)
text(0, -0.035, label="Percentage of sample <= this value", adj=0.5, cex=.8)
```

