---
title: "Graphics R-Markdown"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    keep_md: yes
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: center
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, plotly)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Categorical Data

```{r}
pon <- read.csv("201709-CAH_PulseOfTheNation.csv")

# Pivot Table

pon_pivot <- table(pon$Gender,pon$Political.Affiliation)

# Simple side by side

barplot(pon_pivot, beside = T)

# Prettier

barplot(pon_pivot, ylab="Frequency", xlab="Party", main="Side-By-Side Bar Chart", col=c("blue", "pink", "purple" , "green" ), beside=T, width=.3)

legend("topright", title="Gender", legend= sort(unique(pon$Gender)), fill =c("blue", "pink", "purple" , "green" ), box.lty=0)

# Pie

pon_pie <- table(pon$Political.Affiliation)

pie(pon_pie)

```

## Quantitative Graphs

### Dotplot

```{r}
ggplot(pon, aes(x = Age)) + geom_dotplot(binwidth = .5)

ggplot(pon, aes(x = Age, fill = factor(Political.Affiliation))) + geom_dotplot(binwidth = .8)
```

### Histogram

```{r}
hist(pon$Age)

ggplot(pon, aes(x = Age)) + geom_histogram(binwidth = 5, color = "blue")

```

### Stem and Leaf

```{r}
stem(pon$Income)
```

```{r}
data <- c(310,307,345,324,305,301,290,307)

stem(data)
stem(data, scale = 2)
```

### Boxplot

```{r}
boxplot(data, horizontal = T)

df.stuff <- data.frame(data)
ggplot(df.stuff,aes("stuff",data)) + geom_boxplot() +
    geom_jitter(shape = 15, color = "steelblue", position = position_jitter(width = 0.21)) + coord_flip()
```

## Numerical

### Summary

```{r}
summary(data)
```

### Standard Deviation

```{r}
sd(data)
```


### Standard Deviation by Hand

```{r}
cowboys <- c(310,307,345,324,305,301,290,307)
sdbh <- data.frame("Weight"= cowboys)

```

```{r}
ratings <- c("G","PG","PG-13", "R", "NC-17")
percents <- c(8,24,10,55,3)

pie(percents, ratings)
barplot(percents, names.arg = ratings)
```

```{r}
phones <- c(46,39,19,17)
barplot(phones)
```

```{r}
facebook <- c(78/82,49/70,21/67)
barplot(facebook)
```

```{r}
density <- c(5.5,5.61,4.88,5.07,5.26,5.55,5.36,5.29,5.58,5.65,5.57,5.53,5.62,5.29,5.44,5.34,5.79,5.10,5.27,5.39,5.42,5.47,5.63,5.34,5.46,5.3,5.75,5.68,5.85)
stem(density)
median(density)
```

```{r}
gp <- c(43,80,91,103,137,191,45,80,92,104,138,198,53,81,92,107,139,211,56,81,97,108,144,214,56,81,99,109,145,243,57,82,99,113,147,249,58,83,100,114,156,329,66,83,100,118,162,380,67,84,101,121,174,403,73,88,102,123,178,511,74,89,102,126,179,522,79,91,102,128,184,598)
hist(gp)
boxplot(gp,horizontal = T)
summary(gp)
```

